openapi: 3.0.3
info:
  title: TakuMahi API
  version: '1.0'
  description: The API for TakuMahi.
  x-logo:
    url: ''
servers:
  - url: 'http://localhost:8080/api'
    description: ''
    x-last-modified: 1618956712759
paths:
  /staff:
    summary: Staff List
    description: A list of all Staff.
    get:
      tags:
        - Staff List
      responses:
        '200':
          content:
            application/json:
              schema:
                description: ''
                type: array
                items:
                  $ref: '#/components/schemas/User'
                externalDocs:
                  description: ''
                  url: ''
                example: ''
              example: ''
          description: Response contains the entire Staff list.
      operationId: get All Staff
      summary: Gets All Staff Members
      description: Returns a list of all staff members.
    post:
      requestBody:
        description: Details of Staff Member
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      tags:
        - Staff List
      responses:
        '200':
          content:
            application/json:
              schema:
                description: ''
                type: array
                items:
                  $ref: '#/components/schemas/User'
                externalDocs:
                  description: ''
                  url: ''
                example: ''
              example: ''
              encoding: ''
          description: Response contains the entire Staff list.
          headers: {}
          links: {}
        '201':
          description: New user added.
          x-last-modified: 1618993713660
          headers: {}
          content: {}
          links: {}
        '422':
          description: 'User not added, a User with that ID already exists.'
          x-last-modified: 1618993751972
      operationId: create new user
      summary: Adds a new Staff Member.
      description: Adds a new staff member.
    x-last-modified: 1618956884481
  '/staff/{id}':
    summary: Staff Member
    description: An individual staff member in the database.
    get:
      tags:
        - Staff Member
      parameters:
        - deprecated: false
          name: userId
          description: The ID of the User.
          schema:
            type: string
          in: path
          required: true
          x-last-modified: 1618994119293
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Response contains a single user.
          x-last-modified: 1618994280039
          headers: {}
          links: {}
      operationId: get user by id
      summary: Gets a User by their ID.
      description: Gets a single user by their ID.
    delete:
      tags:
        - Staff Member
      operationId: delete user
      summary: delete specified user
      description: Deletes a user by their ID.
      parameters:
        - name: userId
          in: path
          required: false
          deprecated: false
          x-last-modified: 1618997738244
          description: The ID of the User.
          schema:
            type: string
      responses:
        '204':
          description: Staff Member successfully deleted.
          x-last-modified: 1618997765799
          headers: {}
          content: {}
          links: {}
        '404':
          description: No staff member with that ID was found.
          x-last-modified: 1618997788539
          headers: {}
          content: {}
          links: {}
    x-last-modified: 1618957004765
  '/staff/shifts/{id}':
    summary: Staff Shifts
    description: All shifts assigned to a staff member.
    get:
      tags:
        - Staff Shifts
      operationId: get shifts by user
      summary: Get Shifts by User
      description: Gets all shifts for a specified user.
      parameters:
        - name: id
          in: path
          description: The ID of the User
          required: false
          deprecated: false
          schema:
            type: string
          x-last-modified: 1618998249137
    post:
      tags:
        - Staff Shifts
    x-last-modified: 1618957364214
  /shifts/open:
    summary: Open Shifts
    description: A list of Open Shifts
    get:
      tags:
        - Open Shifts
    post:
      tags:
        - Open Shifts
    x-last-modified: 1618958232749
  '/shifts/open/{id}':
    summary: Open Shift
    description: A single Open Shift
    get:
      tags:
        - Open Shift
    delete:
      tags:
        - Open Shift
    x-last-modified: 1618984121031
  '/staff/{role}':
    summary: Staff by Role
    description: Staff members who fit a specified role.
    get:
      tags:
        - Staff List by Role
    x-last-modified: 1618990034835
  '/staff/{department}':
    summary: Staff by Department
    description: Staff Members who fit a specified department.
    get:
      tags:
        - Staff List by Department
      operationId: get users by department
      summary: Get Users by Department
      description: Gets a list of users in a specified department.
      parameters:
        - name: department
          in: path
          description: The department requested.
          required: false
          deprecated: false
          schema:
            type: string
          x-last-modified: 1618998396969
      responses:
        '200':
          description: Response contains a list of all Users in specified department.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                description: ''
                example: ''
                externalDocs:
                  url: ''
                  description: ''
              encoding: ''
              example: ''
          x-last-modified: 1619000215317
          headers: {}
          links: {}
        '404':
          description: No users in that department were found.
          x-last-modified: 1619000279299
    x-last-modified: 1618990129394
components:
  schemas:
    User:
      required:
        - username
        - idNumber
        - role
        - department
      type: object
      properties:
        username:
          description: The unique username of the user.
          type: string
        idNumber:
          description: The unique ID of the user.
          type: integer
        role:
          description: The role of the user.
          type: string
        department:
          description: The department of the user.
          type: string
        firstName:
          description: The first name of the user.
          type: string
        lastName:
          description: The last name of the user.
          type: string
        email:
          description: The email of the user.
          type: string
      x-last-modified: 1618992390956
  securitySchemes: {}
  headers: {}
  responses: {}
  parameters: {}
tags:
  - name: Staff List
    description: A list of all Staff Members.
    x-last-modified: 1618983952384
  - name: Staff Member
    description: ' A single Staff member.'
    x-last-modified: 1618983940692
  - name: Staff Shifts
    description: List of Shifts for a Staff Member
    x-last-modified: 1618983926915
  - name: Open Shifts List
    description: List of Open Shifts
    x-last-modified: 1618983909230
  - name: Open Shift
    description: A single Open Shift
    x-last-modified: 1618983897996
  - name: Staff List by Role
    description: List of Staff Members by a specified role
    x-last-modified: 1618989901372
  - name: Staff List by Department
    description: List of Staff Members by a specified department.
    x-last-modified: 1618989931533
security: []
